/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m_osi;

import com.osi.controlador.controlador;

/**
 *
 * @author Sora
 */
public class JF_OSI extends javax.swing.JFrame {

    /**
     * Creates new form JF_OSI
     */
    public JF_OSI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JPanel();
        jlblOSI = new javax.swing.JLabel();
        jpIngresoPC = new javax.swing.JPanel();
        jlblIngresarPC = new javax.swing.JLabel();
        jlblIngresarMAC = new javax.swing.JLabel();
        jlblIngresarIP = new javax.swing.JLabel();
        jtxtMAC = new javax.swing.JTextField();
        jtxtIP = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPCS = new javax.swing.JTable();
        jbtnEnviar = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();
        jpEscogerPC = new javax.swing.JPanel();
        jlblEscogerPC = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtPCSe = new javax.swing.JTable();
        jlblPCOrigen = new javax.swing.JLabel();
        jlblPCDestino = new javax.swing.JLabel();
        jlblMACOrigen = new javax.swing.JLabel();
        jlblIPOrigen = new javax.swing.JLabel();
        jlblMACDestino = new javax.swing.JLabel();
        jlblIPDestino = new javax.swing.JLabel();
        jbtnAgregar = new javax.swing.JButton();
        jpDatos = new javax.swing.JPanel();
        jlblIngresarDatos = new javax.swing.JLabel();
        jcbTipoDato = new javax.swing.JComboBox<>();
        jpArchivo = new javax.swing.JPanel();
        jbtnCargar = new javax.swing.JButton();
        jtxtDatoTexto = new javax.swing.JTextField();
        jbtnTexto = new javax.swing.JButton();
        jpDato = new javax.swing.JPanel();
        jlblArchivoT = new javax.swing.JLabel();
        jlblArchivoI = new javax.swing.JLabel();
        jlblTexto = new javax.swing.JLabel();
        jpEnviar = new javax.swing.JPanel();
        jlblEnviarDatos = new javax.swing.JLabel();
        jbtnProbar = new javax.swing.JButton();
        jpOSI = new javax.swing.JPanel();
        jlblAO = new javax.swing.JLabel();
        jlblPO = new javax.swing.JLabel();
        jlblTO = new javax.swing.JLabel();
        jlblSO = new javax.swing.JLabel();
        jlblEO = new javax.swing.JLabel();
        jlblRO = new javax.swing.JLabel();
        jlblFO = new javax.swing.JLabel();
        jlblAD = new javax.swing.JLabel();
        jlblRD = new javax.swing.JLabel();
        jlblTD = new javax.swing.JLabel();
        jlblPD = new javax.swing.JLabel();
        jlblSD = new javax.swing.JLabel();
        jlblFD = new javax.swing.JLabel();
        jlblED = new javax.swing.JLabel();
        jlblIPCO = new javax.swing.JLabel();
        jlblMACO = new javax.swing.JLabel();
        jlblIPCD = new javax.swing.JLabel();
        jlblMACD = new javax.swing.JLabel();
        jlblPCO = new javax.swing.JLabel();
        jlblPCD = new javax.swing.JLabel();
        jmbOSI = new javax.swing.JMenuBar();
        jmPC = new javax.swing.JMenu();
        jmiIngresarPC = new javax.swing.JMenuItem();
        jmiEscogerPCOD = new javax.swing.JMenuItem();
        jmOSI = new javax.swing.JMenu();
        jmiDatos = new javax.swing.JMenuItem();
        jmiEnviar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jlblOSI.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sora\\Desktop\\model_osi.jpg")); // NOI18N

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblOSI)
                .addGap(190, 190, 190))
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jlblOSI)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlblIngresarPC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblIngresarPC.setText("INGRESAR PC");

        jlblIngresarMAC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblIngresarMAC.setText("Ingresar MAC:");

        jlblIngresarIP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblIngresarIP.setText("Ingresar IP:");

        jtxtMAC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtxtIP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtPCS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PC", "MAC", "IP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtPCS);

        jbtnEnviar.setText("Enviar");

        jbtnLimpiar.setText("Limpiar");

        javax.swing.GroupLayout jpIngresoPCLayout = new javax.swing.GroupLayout(jpIngresoPC);
        jpIngresoPC.setLayout(jpIngresoPCLayout);
        jpIngresoPCLayout.setHorizontalGroup(
            jpIngresoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpIngresoPCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpIngresoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblIngresarMAC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblIngresarIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jpIngresoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtMAC)
                    .addComponent(jtxtIP, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addGap(184, 184, 184))
            .addGroup(jpIngresoPCLayout.createSequentialGroup()
                .addGroup(jpIngresoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpIngresoPCLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jlblIngresarPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpIngresoPCLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jpIngresoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpIngresoPCLayout.createSequentialGroup()
                                .addComponent(jbtnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addComponent(jbtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addGap(63, 63, 63))
        );
        jpIngresoPCLayout.setVerticalGroup(
            jpIngresoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIngresoPCLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jlblIngresarPC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpIngresoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblIngresarMAC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtMAC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpIngresoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblIngresarIP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jpIngresoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );

        jpEscogerPC.setPreferredSize(new java.awt.Dimension(400, 283));

        jlblEscogerPC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblEscogerPC.setText("ESCOGER PC");

        jtPCSe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PC", "MAC", "IP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtPCSe);

        jlblPCOrigen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblPCOrigen.setText("PC de Origen");

        jlblPCDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblPCDestino.setText("PC de Destino");

        jlblMACOrigen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jlblIPOrigen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jlblMACDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jlblIPDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jbtnAgregar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtnAgregar.setText("+");

        javax.swing.GroupLayout jpEscogerPCLayout = new javax.swing.GroupLayout(jpEscogerPC);
        jpEscogerPC.setLayout(jpEscogerPCLayout);
        jpEscogerPCLayout.setHorizontalGroup(
            jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEscogerPCLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jlblEscogerPC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEscogerPCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEscogerPCLayout.createSequentialGroup()
                        .addGroup(jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblMACOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblIPOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpEscogerPCLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jlblPCOrigen)))
                        .addGap(18, 18, 18)
                        .addComponent(jbtnAgregar)
                        .addGroup(jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEscogerPCLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jlblPCDestino))
                            .addGroup(jpEscogerPCLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblIPDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblMACDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEscogerPCLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
        );
        jpEscogerPCLayout.setVerticalGroup(
            jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEscogerPCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblEscogerPC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEscogerPCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblPCOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblPCDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEscogerPCLayout.createSequentialGroup()
                                .addComponent(jlblMACDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlblIPOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblIPDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jlblMACOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpEscogerPCLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbtnAgregar)))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        jpDatos.setPreferredSize(new java.awt.Dimension(400, 283));

        jlblIngresarDatos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblIngresarDatos.setText("Ingresar Datos");

        jcbTipoDato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbTipoDato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Texto", "Archivo" }));

        jbtnCargar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnCargar.setText("Cargar Archivo");

        javax.swing.GroupLayout jpArchivoLayout = new javax.swing.GroupLayout(jpArchivo);
        jpArchivo.setLayout(jpArchivoLayout);
        jpArchivoLayout.setHorizontalGroup(
            jpArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpArchivoLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jbtnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jpArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpArchivoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jtxtDatoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jpArchivoLayout.setVerticalGroup(
            jpArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpArchivoLayout.createSequentialGroup()
                .addComponent(jbtnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
            .addGroup(jpArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpArchivoLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jtxtDatoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jbtnTexto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnTexto.setText("Cargar");

        javax.swing.GroupLayout jpDatoLayout = new javax.swing.GroupLayout(jpDato);
        jpDato.setLayout(jpDatoLayout);
        jpDatoLayout.setHorizontalGroup(
            jpDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
            .addGroup(jpDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jlblArchivoT, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
            .addGroup(jpDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jlblArchivoI, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
            .addGroup(jpDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jlblTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
        );
        jpDatoLayout.setVerticalGroup(
            jpDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
            .addGroup(jpDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jlblArchivoT, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
            .addGroup(jpDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jlblArchivoI, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
            .addGroup(jpDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jlblTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpDatosLayout = new javax.swing.GroupLayout(jpDatos);
        jpDatos.setLayout(jpDatosLayout);
        jpDatosLayout.setHorizontalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jlblIngresarDatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jpArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jcbTipoDato, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosLayout.createSequentialGroup()
                        .addComponent(jbtnTexto)
                        .addGap(84, 84, 84)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpDatosLayout.setVerticalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblIngresarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbTipoDato)
                    .addComponent(jpArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpEnviar.setPreferredSize(new java.awt.Dimension(400, 283));

        jlblEnviarDatos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblEnviarDatos.setText("Enviar Datos");

        jbtnProbar.setText("PROBAR");

        jlblAO.setText("Aplicación");

        jlblPO.setText("Presentación");

        jlblTO.setText("Transporte");

        jlblSO.setText("Sesión");

        jlblEO.setText("Enlace de datos");

        jlblRO.setText("Red");

        jlblFO.setText("Física");

        jlblAD.setText("Aplicación");

        jlblRD.setText("Red");

        jlblTD.setText("Transporte");

        jlblPD.setText("Presentación");

        jlblSD.setText("Sesión");

        jlblFD.setText("Física");

        jlblED.setText("Enlace de datos");

        jlblIPCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PC.png"))); // NOI18N

        jlblIPCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PC.png"))); // NOI18N

        javax.swing.GroupLayout jpOSILayout = new javax.swing.GroupLayout(jpOSI);
        jpOSI.setLayout(jpOSILayout);
        jpOSILayout.setHorizontalGroup(
            jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOSILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlblPCO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblMACO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblFO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblEO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblRO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblTO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblSO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblPO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblAO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblIPCO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 429, Short.MAX_VALUE)
                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblFD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblED, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblRD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblTD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblSD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblPD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblAD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblIPCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblMACD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblPCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpOSILayout.setVerticalGroup(
            jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOSILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblIPCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblIPCO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblMACO, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblMACD, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblPCO, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblPCD, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpOSILayout.createSequentialGroup()
                        .addComponent(jlblAD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblPD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblSD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblTD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jlblRD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblED, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblFD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpOSILayout.createSequentialGroup()
                        .addComponent(jlblAO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblPO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblSO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblTO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jlblRO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblEO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblFO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpEnviarLayout = new javax.swing.GroupLayout(jpEnviar);
        jpEnviar.setLayout(jpEnviarLayout);
        jpEnviarLayout.setHorizontalGroup(
            jpEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnviarLayout.createSequentialGroup()
                .addGroup(jpEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEnviarLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jbtnProbar, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpEnviarLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jlblEnviarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpOSI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpEnviarLayout.setVerticalGroup(
            jpEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnviarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblEnviarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jbtnProbar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEnviarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpOSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jmPC.setText("PC");

        jmiIngresarPC.setText("Ingresar PC");
        jmiIngresarPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIngresarPCActionPerformed(evt);
            }
        });
        jmPC.add(jmiIngresarPC);

        jmiEscogerPCOD.setText("Escoger PCs");
        jmPC.add(jmiEscogerPCOD);

        jmbOSI.add(jmPC);

        jmOSI.setText("OSI");

        jmiDatos.setText("Ingresar Datos");
        jmOSI.add(jmiDatos);

        jmiEnviar.setText("Enviar");
        jmOSI.add(jmiEnviar);

        jmbOSI.add(jmOSI);

        setJMenuBar(jmbOSI);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpIngresoPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpEscogerPC, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpIngresoPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpEscogerPC, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiIngresarPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIngresarPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiIngresarPCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        JF_OSI view = new JF_OSI();
        controlador control = new controlador(view);
        view.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton jbtnAgregar;
    public javax.swing.JButton jbtnCargar;
    public javax.swing.JButton jbtnEnviar;
    public javax.swing.JButton jbtnLimpiar;
    public javax.swing.JButton jbtnProbar;
    public javax.swing.JButton jbtnTexto;
    public javax.swing.JComboBox<String> jcbTipoDato;
    private javax.swing.JLabel jlblAD;
    private javax.swing.JLabel jlblAO;
    public javax.swing.JLabel jlblArchivoI;
    public javax.swing.JLabel jlblArchivoT;
    private javax.swing.JLabel jlblED;
    private javax.swing.JLabel jlblEO;
    private javax.swing.JLabel jlblEnviarDatos;
    private javax.swing.JLabel jlblEscogerPC;
    private javax.swing.JLabel jlblFD;
    private javax.swing.JLabel jlblFO;
    private javax.swing.JLabel jlblIPCD;
    private javax.swing.JLabel jlblIPCO;
    public javax.swing.JLabel jlblIPDestino;
    public javax.swing.JLabel jlblIPOrigen;
    private javax.swing.JLabel jlblIngresarDatos;
    private javax.swing.JLabel jlblIngresarIP;
    private javax.swing.JLabel jlblIngresarMAC;
    private javax.swing.JLabel jlblIngresarPC;
    public javax.swing.JLabel jlblMACD;
    public javax.swing.JLabel jlblMACDestino;
    public javax.swing.JLabel jlblMACO;
    public javax.swing.JLabel jlblMACOrigen;
    private javax.swing.JLabel jlblOSI;
    public javax.swing.JLabel jlblPCD;
    private javax.swing.JLabel jlblPCDestino;
    public javax.swing.JLabel jlblPCO;
    private javax.swing.JLabel jlblPCOrigen;
    private javax.swing.JLabel jlblPD;
    private javax.swing.JLabel jlblPO;
    private javax.swing.JLabel jlblRD;
    private javax.swing.JLabel jlblRO;
    private javax.swing.JLabel jlblSD;
    private javax.swing.JLabel jlblSO;
    private javax.swing.JLabel jlblTD;
    private javax.swing.JLabel jlblTO;
    public javax.swing.JLabel jlblTexto;
    private javax.swing.JMenu jmOSI;
    private javax.swing.JMenu jmPC;
    private javax.swing.JMenuBar jmbOSI;
    public javax.swing.JMenuItem jmiDatos;
    public javax.swing.JMenuItem jmiEnviar;
    public javax.swing.JMenuItem jmiEscogerPCOD;
    public javax.swing.JMenuItem jmiIngresarPC;
    private javax.swing.JPanel jpArchivo;
    private javax.swing.JPanel jpDato;
    public javax.swing.JPanel jpDatos;
    public javax.swing.JPanel jpEnviar;
    public javax.swing.JPanel jpEscogerPC;
    public javax.swing.JPanel jpIngresoPC;
    public javax.swing.JPanel jpOSI;
    public javax.swing.JPanel jpPrincipal;
    public javax.swing.JTable jtPCS;
    public javax.swing.JTable jtPCSe;
    public javax.swing.JTextField jtxtDatoTexto;
    public javax.swing.JTextField jtxtIP;
    public javax.swing.JTextField jtxtMAC;
    // End of variables declaration//GEN-END:variables
}
