/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m_osi;

import com.osi.controlador.controlador;

/**
 *
 * @author Sora
 */
public class JF_OSI extends javax.swing.JFrame {

    /**
     * Creates new form JF_OSI
     */
    public JF_OSI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JPanel();
        jlblOSI = new javax.swing.JLabel();
        jpIngresoPC = new javax.swing.JPanel();
        jlblIngresarPC = new javax.swing.JLabel();
        jlblIngresarMAC = new javax.swing.JLabel();
        jlblIngresarIP = new javax.swing.JLabel();
        jtxtMAC = new javax.swing.JTextField();
        jtxtIP = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPCS = new javax.swing.JTable();
        jbtnEnviar = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();
        jpEscogerPC = new javax.swing.JPanel();
        jlblEscogerPC = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtPCSe = new javax.swing.JTable();
        jlblPCOrigen = new javax.swing.JLabel();
        jlblPCDestino = new javax.swing.JLabel();
        jlblMACOrigen = new javax.swing.JLabel();
        jlblIPOrigen = new javax.swing.JLabel();
        jlblMACDestino = new javax.swing.JLabel();
        jlblIPDestino = new javax.swing.JLabel();
        jbtnAgregar = new javax.swing.JButton();
        jpDatos = new javax.swing.JPanel();
        jlblIngresarDatos = new javax.swing.JLabel();
        jcbTipoDato = new javax.swing.JComboBox<>();
        jpArchivo = new javax.swing.JPanel();
        jbtnCargar = new javax.swing.JButton();
        jtxtDatoTexto = new javax.swing.JTextField();
        jbtnTexto = new javax.swing.JButton();
        jlblMostrar = new javax.swing.JLabel();
        jpEnviar = new javax.swing.JPanel();
        jlblEnviarDatos = new javax.swing.JLabel();
        jbtnProbar = new javax.swing.JButton();
        jpOSI = new javax.swing.JPanel();
        jlblAO = new javax.swing.JLabel();
        jlblPO = new javax.swing.JLabel();
        jlblTO = new javax.swing.JLabel();
        jlblSO = new javax.swing.JLabel();
        jlblEO = new javax.swing.JLabel();
        jlblRO = new javax.swing.JLabel();
        jlblFO = new javax.swing.JLabel();
        jlblIPCO = new javax.swing.JLabel();
        jlblMACO = new javax.swing.JLabel();
        jlblPCO = new javax.swing.JLabel();
        jlblMoveAD = new javax.swing.JLabel();
        jlblRD = new javax.swing.JLabel();
        jlblSD = new javax.swing.JLabel();
        jlblFD = new javax.swing.JLabel();
        jlblIPCD = new javax.swing.JLabel();
        jlblPD = new javax.swing.JLabel();
        jlblMACD = new javax.swing.JLabel();
        jlblTD = new javax.swing.JLabel();
        jlblAD = new javax.swing.JLabel();
        jlblPCD = new javax.swing.JLabel();
        jlblED = new javax.swing.JLabel();
        jlblMovePO = new javax.swing.JLabel();
        jlblMoveSD = new javax.swing.JLabel();
        jlblMoveTO = new javax.swing.JLabel();
        jlblMoveED = new javax.swing.JLabel();
        jlblMoveRD = new javax.swing.JLabel();
        jlblMoveFD = new javax.swing.JLabel();
        jlblMoveAO = new javax.swing.JLabel();
        jlblMovePD = new javax.swing.JLabel();
        jlblMoveSO = new javax.swing.JLabel();
        jlblMoveTD = new javax.swing.JLabel();
        jlblMoveEO = new javax.swing.JLabel();
        jlblMoveFO = new javax.swing.JLabel();
        jlblMoveRO = new javax.swing.JLabel();
        jpDiagrama = new javax.swing.JPanel();
        jbntGuardar = new javax.swing.JButton();
        jlblBit = new javax.swing.JLabel();
        jmbOSI = new javax.swing.JMenuBar();
        jmPC = new javax.swing.JMenu();
        jmiIngresarPC = new javax.swing.JMenuItem();
        jmiEscogerPCOD = new javax.swing.JMenuItem();
        jmOSI = new javax.swing.JMenu();
        jmiDatos = new javax.swing.JMenuItem();
        jmiEnviar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jlblOSI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblOSI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/model_osi.jpg"))); // NOI18N

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jlblOSI, javax.swing.GroupLayout.PREFERRED_SIZE, 1378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jlblOSI, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jlblIngresarPC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblIngresarPC.setText("INGRESAR PC");

        jlblIngresarMAC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblIngresarMAC.setText("Ingresar MAC:");

        jlblIngresarIP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblIngresarIP.setText("Ingresar IP:");

        jtxtMAC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtxtIP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtPCS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PC", "MAC", "IP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtPCS);

        jbtnEnviar.setText("Enviar");

        jbtnLimpiar.setText("Limpiar");

        javax.swing.GroupLayout jpIngresoPCLayout = new javax.swing.GroupLayout(jpIngresoPC);
        jpIngresoPC.setLayout(jpIngresoPCLayout);
        jpIngresoPCLayout.setHorizontalGroup(
            jpIngresoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIngresoPCLayout.createSequentialGroup()
                .addGroup(jpIngresoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpIngresoPCLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1))
                    .addGroup(jpIngresoPCLayout.createSequentialGroup()
                        .addGap(515, 515, 515)
                        .addComponent(jbtnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpIngresoPCLayout.createSequentialGroup()
                .addContainerGap(553, Short.MAX_VALUE)
                .addGroup(jpIngresoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpIngresoPCLayout.createSequentialGroup()
                        .addGroup(jpIngresoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblIngresarMAC, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblIngresarIP, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpIngresoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtMAC)
                            .addComponent(jtxtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpIngresoPCLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jlblIngresarPC))
                    .addGroup(jpIngresoPCLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jbtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(474, 474, 474))
        );
        jpIngresoPCLayout.setVerticalGroup(
            jpIngresoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIngresoPCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblIngresarPC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpIngresoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblIngresarMAC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtMAC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpIngresoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblIngresarIP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jpIngresoPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnEnviar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );

        jpEscogerPC.setPreferredSize(new java.awt.Dimension(400, 283));

        jlblEscogerPC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblEscogerPC.setText("ESCOGER PC");

        jtPCSe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PC", "MAC", "IP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtPCSe);

        jlblPCOrigen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblPCOrigen.setText("PC de Origen");

        jlblPCDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblPCDestino.setText("PC de Destino");

        jlblMACOrigen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jlblIPOrigen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jlblMACDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jlblIPDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jbtnAgregar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtnAgregar.setText("+");

        javax.swing.GroupLayout jpEscogerPCLayout = new javax.swing.GroupLayout(jpEscogerPC);
        jpEscogerPC.setLayout(jpEscogerPCLayout);
        jpEscogerPCLayout.setHorizontalGroup(
            jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEscogerPCLayout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addGroup(jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEscogerPCLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblMACOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblIPOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpEscogerPCLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jlblPCOrigen)))
                        .addGap(18, 18, 18)
                        .addComponent(jbtnAgregar)
                        .addGroup(jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEscogerPCLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jlblPCDestino))
                            .addGroup(jpEscogerPCLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblIPDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblMACDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEscogerPCLayout.createSequentialGroup()
                            .addComponent(jlblEscogerPC)
                            .addGap(200, 200, 200))))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        jpEscogerPCLayout.setVerticalGroup(
            jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEscogerPCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblEscogerPC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEscogerPCLayout.createSequentialGroup()
                        .addGroup(jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblPCOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblPCDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEscogerPCLayout.createSequentialGroup()
                                .addComponent(jlblMACDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpEscogerPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlblIPOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblIPDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jlblMACOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpEscogerPCLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jbtnAgregar)))
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jpDatos.setPreferredSize(new java.awt.Dimension(400, 283));

        jlblIngresarDatos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblIngresarDatos.setText("Ingresar Datos");

        jcbTipoDato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbTipoDato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Texto", "Archivo" }));

        jbtnCargar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnCargar.setText("Cargar Archivo");

        javax.swing.GroupLayout jpArchivoLayout = new javax.swing.GroupLayout(jpArchivo);
        jpArchivo.setLayout(jpArchivoLayout);
        jpArchivoLayout.setHorizontalGroup(
            jpArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpArchivoLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jbtnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jpArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpArchivoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jtxtDatoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jpArchivoLayout.setVerticalGroup(
            jpArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpArchivoLayout.createSequentialGroup()
                .addComponent(jbtnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(jpArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpArchivoLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jtxtDatoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jbtnTexto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnTexto.setText("Cargar");

        jlblMostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpDatosLayout = new javax.swing.GroupLayout(jpDatos);
        jpDatos.setLayout(jpDatosLayout);
        jpDatosLayout.setHorizontalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addContainerGap(519, Short.MAX_VALUE)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosLayout.createSequentialGroup()
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDatosLayout.createSequentialGroup()
                                .addComponent(jpArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(jcbTipoDato, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpDatosLayout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(jlblIngresarDatos))
                            .addGroup(jpDatosLayout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addComponent(jbtnTexto)))
                        .addGap(501, 501, 501))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosLayout.createSequentialGroup()
                        .addComponent(jlblMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(528, 528, 528))))
        );
        jpDatosLayout.setVerticalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblIngresarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbTipoDato)
                    .addComponent(jpArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnTexto)
                .addGap(42, 42, 42)
                .addComponent(jlblMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addGap(423, 423, 423))
        );

        jpEnviar.setPreferredSize(new java.awt.Dimension(400, 283));

        jlblEnviarDatos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblEnviarDatos.setText("Enviar Datos");

        jbtnProbar.setText("Probar");
        jbtnProbar.setFocusPainted(false);

        jpOSI.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jlblAO.setText("Aplicación");

        jlblPO.setText("Presentación");

        jlblTO.setText("Transporte");

        jlblSO.setText("Sesión");

        jlblEO.setText("Enlace de datos");

        jlblRO.setText("Red");

        jlblFO.setText("Física");

        jlblIPCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PC.png"))); // NOI18N

        jlblMoveAD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlblRD.setText("Red");

        jlblSD.setText("Sesión");

        jlblFD.setText("Física");

        jlblIPCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PC.png"))); // NOI18N

        jlblPD.setText("Presentación");

        jlblTD.setText("Transporte");

        jlblAD.setText("Aplicación");

        jlblED.setText("Enlace de datos");

        jlblMoveSD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jlblMoveED.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jlblMoveRD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jlblMoveFD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jlblMovePD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jlblMoveTD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jpDiagramaLayout = new javax.swing.GroupLayout(jpDiagrama);
        jpDiagrama.setLayout(jpDiagramaLayout);
        jpDiagramaLayout.setHorizontalGroup(
            jpDiagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 897, Short.MAX_VALUE)
        );
        jpDiagramaLayout.setVerticalGroup(
            jpDiagramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jbntGuardar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbntGuardar.setText("Guardar Archivo");

        jlblBit.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        javax.swing.GroupLayout jpOSILayout = new javax.swing.GroupLayout(jpOSI);
        jpOSI.setLayout(jpOSILayout);
        jpOSILayout.setHorizontalGroup(
            jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOSILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpOSILayout.createSequentialGroup()
                        .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlblAO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblPCO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblMACO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblIPCO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpOSILayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlblMoveAO, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlblMoveAD, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpOSILayout.createSequentialGroup()
                                .addGap(413, 413, 413)
                                .addComponent(jbntGuardar)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jpOSILayout.createSequentialGroup()
                        .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlblPO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblSO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblFO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblTO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblRO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblEO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpOSILayout.createSequentialGroup()
                                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblMoveRO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblMoveSO, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblMoveRD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblMoveSD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpOSILayout.createSequentialGroup()
                                .addComponent(jlblMoveTO, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlblMoveTD, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpOSILayout.createSequentialGroup()
                                .addComponent(jlblMovePO, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlblMovePD, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpOSILayout.createSequentialGroup()
                                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpOSILayout.createSequentialGroup()
                                        .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jlblMoveEO, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                            .addComponent(jlblMoveFO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlblMoveFD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlblMoveED, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jpOSILayout.createSequentialGroup()
                                        .addComponent(jpDiagrama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(6, 6, 6))
                            .addGroup(jpOSILayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jlblBit, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlblPD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlblTD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlblMACD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlblPCD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblIPCD)
                                    .addComponent(jlblRD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jlblFD, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblED, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jlblAD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlblSD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jpOSILayout.setVerticalGroup(
            jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOSILayout.createSequentialGroup()
                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpOSILayout.createSequentialGroup()
                        .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblIPCO)
                            .addGroup(jpOSILayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jbntGuardar)))
                        .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpOSILayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlblMACO, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlblPCO, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpOSILayout.createSequentialGroup()
                                        .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlblMoveAD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlblAO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlblAD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(38, 38, 38)
                                        .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jpOSILayout.createSequentialGroup()
                                                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jlblPO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jlblMovePO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(32, 32, 32)
                                                .addComponent(jlblSO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)
                                                .addComponent(jlblTO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jpOSILayout.createSequentialGroup()
                                                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jlblMoveSO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jlblSD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jlblMoveSD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(30, 30, 30)
                                                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jlblMoveTO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jlblMoveTD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jlblMoveAO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpOSILayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(jlblMovePD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpOSILayout.createSequentialGroup()
                                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblRO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblMoveRD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlblMoveED, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblEO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblED, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblMoveEO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jpOSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlblFO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblMoveFD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblFD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblMoveFO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jlblMoveRO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpOSILayout.createSequentialGroup()
                        .addComponent(jlblIPCD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblMACD, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblPCD, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jlblPD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jlblTD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jlblRD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDiagrama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblBit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpEnviarLayout = new javax.swing.GroupLayout(jpEnviar);
        jpEnviar.setLayout(jpEnviarLayout);
        jpEnviarLayout.setHorizontalGroup(
            jpEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEnviarLayout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(jpEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblEnviarDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEnviarLayout.createSequentialGroup()
                        .addComponent(jbtnProbar)
                        .addGap(42, 42, 42)))
                .addGap(503, 503, 503))
            .addGroup(jpEnviarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpOSI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jpEnviarLayout.setVerticalGroup(
            jpEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnviarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblEnviarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnProbar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpOSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jmPC.setText("PC");

        jmiIngresarPC.setText("Ingresar PC");
        jmPC.add(jmiIngresarPC);

        jmiEscogerPCOD.setText("Escoger PCs");
        jmPC.add(jmiEscogerPCOD);

        jmbOSI.add(jmPC);

        jmOSI.setText("OSI");

        jmiDatos.setText("Ingresar Datos");
        jmOSI.add(jmiDatos);

        jmiEnviar.setText("Enviar");
        jmOSI.add(jmiEnviar);

        jmbOSI.add(jmOSI);

        setJMenuBar(jmbOSI);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpIngresoPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 167, Short.MAX_VALUE)
                    .addComponent(jpEscogerPC, javax.swing.GroupLayout.DEFAULT_SIZE, 1163, Short.MAX_VALUE)
                    .addGap(0, 166, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1496, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(141, Short.MAX_VALUE)
                    .addComponent(jpEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 1215, Short.MAX_VALUE)
                    .addContainerGap(140, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpIngresoPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 69, Short.MAX_VALUE)
                    .addComponent(jpEscogerPC, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                    .addGap(0, 71, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(66, Short.MAX_VALUE)
                    .addComponent(jpEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                    .addContainerGap(67, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        JF_OSI view = new JF_OSI();
        controlador control = new controlador(view);
        view.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton jbntGuardar;
    public javax.swing.JButton jbtnAgregar;
    public javax.swing.JButton jbtnCargar;
    public javax.swing.JButton jbtnEnviar;
    public javax.swing.JButton jbtnLimpiar;
    public javax.swing.JButton jbtnProbar;
    public javax.swing.JButton jbtnTexto;
    public javax.swing.JComboBox<String> jcbTipoDato;
    public javax.swing.JLabel jlblAD;
    public javax.swing.JLabel jlblAO;
    public javax.swing.JLabel jlblBit;
    public javax.swing.JLabel jlblED;
    public javax.swing.JLabel jlblEO;
    private javax.swing.JLabel jlblEnviarDatos;
    private javax.swing.JLabel jlblEscogerPC;
    public javax.swing.JLabel jlblFD;
    public javax.swing.JLabel jlblFO;
    private javax.swing.JLabel jlblIPCD;
    private javax.swing.JLabel jlblIPCO;
    public javax.swing.JLabel jlblIPDestino;
    public javax.swing.JLabel jlblIPOrigen;
    private javax.swing.JLabel jlblIngresarDatos;
    private javax.swing.JLabel jlblIngresarIP;
    private javax.swing.JLabel jlblIngresarMAC;
    private javax.swing.JLabel jlblIngresarPC;
    public javax.swing.JLabel jlblMACD;
    public javax.swing.JLabel jlblMACDestino;
    public javax.swing.JLabel jlblMACO;
    public javax.swing.JLabel jlblMACOrigen;
    public javax.swing.JLabel jlblMostrar;
    public javax.swing.JLabel jlblMoveAD;
    public javax.swing.JLabel jlblMoveAO;
    public javax.swing.JLabel jlblMoveED;
    public javax.swing.JLabel jlblMoveEO;
    public javax.swing.JLabel jlblMoveFD;
    public javax.swing.JLabel jlblMoveFO;
    public javax.swing.JLabel jlblMovePD;
    public javax.swing.JLabel jlblMovePO;
    public javax.swing.JLabel jlblMoveRD;
    public javax.swing.JLabel jlblMoveRO;
    public javax.swing.JLabel jlblMoveSD;
    public javax.swing.JLabel jlblMoveSO;
    public javax.swing.JLabel jlblMoveTD;
    public javax.swing.JLabel jlblMoveTO;
    private javax.swing.JLabel jlblOSI;
    public javax.swing.JLabel jlblPCD;
    private javax.swing.JLabel jlblPCDestino;
    public javax.swing.JLabel jlblPCO;
    private javax.swing.JLabel jlblPCOrigen;
    public javax.swing.JLabel jlblPD;
    public javax.swing.JLabel jlblPO;
    public javax.swing.JLabel jlblRD;
    public javax.swing.JLabel jlblRO;
    public javax.swing.JLabel jlblSD;
    public javax.swing.JLabel jlblSO;
    public javax.swing.JLabel jlblTD;
    public javax.swing.JLabel jlblTO;
    private javax.swing.JMenu jmOSI;
    private javax.swing.JMenu jmPC;
    private javax.swing.JMenuBar jmbOSI;
    public javax.swing.JMenuItem jmiDatos;
    public javax.swing.JMenuItem jmiEnviar;
    public javax.swing.JMenuItem jmiEscogerPCOD;
    public javax.swing.JMenuItem jmiIngresarPC;
    private javax.swing.JPanel jpArchivo;
    public javax.swing.JPanel jpDatos;
    public javax.swing.JPanel jpDiagrama;
    public javax.swing.JPanel jpEnviar;
    public javax.swing.JPanel jpEscogerPC;
    public javax.swing.JPanel jpIngresoPC;
    public javax.swing.JPanel jpOSI;
    public javax.swing.JPanel jpPrincipal;
    public javax.swing.JTable jtPCS;
    public javax.swing.JTable jtPCSe;
    public javax.swing.JTextField jtxtDatoTexto;
    public javax.swing.JTextField jtxtIP;
    public javax.swing.JTextField jtxtMAC;
    // End of variables declaration//GEN-END:variables
}
